### ISSUE TITLE
mp3 file created with audio and video also

### ISSUE THREAD

**Issue by swathionchip** [codealchemist/youtube-audio-server#12]
Hi All,

I Downloaded the source code from git hub and I gave the "yas --id 2zYDMN4h2hY --file sample.mp3" this command. So sample.mp3 file created with audio and video also.

I need only audio no video.

What is the procedure for this project for audio file.

Could you please tell me the Sequence of steps in this project for testing.

Thanks In advance.

Regards,
Swathi.

**Comment by codealchemist** [comment]
Hi @swathionchip !
I was able to reproduce this issue.
I'll try to get some time to work on it.

Thanks for reporting it!
