### ISSUE TITLE
Error: Cannot find ffmpeg

### ISSUE THREAD

**Issue by smiledev1230** [codealchemist/youtube-audio-server#14]
it works well on local but not on node server.
Error: Cannot find ffmpeg
    at /user_code/node_modules/youtube-audio-server/node_modules/fluent-ffmpeg/lib/processor.js:136:22
    at /user_code/node_modules/youtube-audio-server/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9
    at /user_code/node_modules/youtube-audio-server/node_modules/async/dist/async.js:473:16
    at next (/user_code/node_modules/youtube-audio-server/node_modules/async/dist/async.js:5329:29)
    at /user_code/node_modules/youtube-audio-server/node_modules/async/dist/async.js:969:16

**Comment by codealchemist** [comment]
This is expected to happen if `ffmpeg` is not installed on the host.
Check out:
https://www.npmjs.com/package/fluent-ffmpeg

So you'll need to install `ffmpeg` on your server for it to work.

Thx!
