### ISSUE TITLE
Please update ytdl-core

### ISSUE THREAD

**Issue by tva2000hn** [codealchemist/youtube-audio-server#20]
Please update the ytdl-core to v 0.29.1 or live stream will not work

**Comment by stephane-r** [comment]
#21 

Submit PR for upgrade this repo and fix some audit security dependencies.

**Comment by stephane-r** [comment]
@tva2000hn PR merged. This issue can be closed :)

**Comment by behr-davide** [comment]
Thanks for the fix! Can you publish the latest changes to NPM? Currently, npm i --save codealchemist/youtube-audio-server will install this package with the latest changes to the package.json, but npm i --save youtube-audio-server still contains the stale ytdl-core dependency

**Comment by domkinger** [comment]
> Thanks for the fix! Can you publish the latest changes to NPM? Currently, npm i --save codealchemist/youtube-audio-server will install this package with the latest changes to the package.json, but npm i --save youtube-audio-server still contains the stale ytdl-core dependency

seconding this!
