### ISSUE TITLE
Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by alberto98fx** [codealchemist/youtube-audio-server#5]
When running tests and passing videoId I get this: 

Error: Input stream error: Could not extract signature deciphering actions

**Comment by flantengfei** [comment]
Got the same issue.

**Comment by TrimA74** [comment]
Same when i do : 
- sudo yas
- visit http://localhost:80/videoID

**Comment by codealchemist** [comment]
Hey guys!
I'm able to reproduce.
Apparently it's an issue with `ytdl-core`.
I'll look for a fix and post back here.

**Comment by codealchemist** [comment]
Just released version 2.1.4.
Thanks for reporting the issue!
:)
