### ISSUE TITLE
can't install on heroku

### ISSUE THREAD

**Issue by tva2000hn** [codealchemist/youtube-audio-server#7]
i tried to install the latest version of this app on heroku and it doesnt work

**Comment by pkpp1233** [comment]
+1

**Comment by thecooltechguy** [comment]
This is happening because yas is trying to use port 80, but Heroku doesn't allow that port. In fact, I got the same problem running the latest yas locally, and by running "sudo yas", my laptop gave the program permission to use port 80.

**Comment by codealchemist** [comment]
You can change default port with the `PORT` env var.
Like: `PORT=9000 yas`

The problem I found on Heroku is that `ffmpeg` is not available, and it's required for this module to work.
I think you can set which Linux dependencies you want to be installed on Heroku but I wasn't able to make it work.

**Comment by edwinharly** [comment]
Yesterday I was trying to deploy it to Heroku, you need to add heroku's ffmpeg buildpack to your Heroku configuration.

**Comment by codealchemist** [comment]
Yay! Just tried installing the **ffmpeg buildpack** and got it working on Heroku.
Installed with:
`heroku buildpacks:add https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git`

Thanks @edwinharly :)

**Comment by tva2000hn** [comment]
Thank you very much! It works great now!
